version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
before_build:
- cmd: "nuget restore \".\\Slack.Automation\\Promact.ERP.sln\"\nnpm install -g typings tslint typescript \ncd \".\\Slack.Automation\\Promact.Erp.Web\"\nnpm install\ncd \"..\\..\""
build:
  parallel: true
  verbosity: minimal
test_script:
- cmd: '".\Slack.Automation\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" ".\Slack.Automation\Promact.Core.Test\bin\Release\Promact.Core.Test.dll" -appveyor'
notifications:
- provider: Slack
  auth_token:
    secure: a8gvDGvmvaulk5ajhx+cTq9Eebui6VidpqGMXmx7HKu5SHwnSKZGveU/BclA+/hifPjQMWUNyvWIFX8LpSDcPQ==
  channel: slack-automation-mvc
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false