version: 1.0.{build}
branches:
  only:
  - dev
before_build:
- cmd: "nuget restore \".\\Slack.Automation\\Promact.ERP.sln\"\nnpm install -g typings tslint typescript \ncd \".\\Slack.Automation\\Promact.Erp.Web\"\nnpm install\ncd \"..\\..\""
build:
  parallel: true
  verbosity: detailed
test_script:
- cmd: xunit.console.clr4 **\Promact.Core.Test.dll /appveyor