version: 1.0.{build}
branches:
  only:
  - dev
configuration: Release
platform: Any CPU
before_build:
- ps: "nuget restore \".\\Slack.Automation\\Promact.ERP.sln\"\nnpm install -g typings tslint typescript \nnpm install \".\\Slack.Automation\\Promact.Erp.Web\""
build:
  parallel: true
  verbosity: minimal
test_script:
- cmd: xunit.console.clr4 <assembly> /appveyor